CATALINA_OPTS="-server"
CATALINA_OPTS="$CATALINA_OPTS -Dcom.sun.management.jmxremote=true"
CATALINA_OPTS="$CATALINA_OPTS -Djava.security.egd=file:/dev/./urandom"
CATALINA_OPTS="$CATALINA_OPTS -Daqcu_reports_webservice=$aqcu_reports_webservice"
CATALINA_OPTS="$CATALINA_OPTS -Dhttp_port=$aqcu_ui_http_port"
CATALINA_OPTS="$CATALINA_OPTS -Dhttps_port=$aqcu_ui_https_port"
CATALINA_OPTS="$CATALINA_OPTS -Dcida_auth_service_endpoint=$cida_auth_service_endpoint"
CATALINA_OPTS="$CATALINA_OPTS -Daquarius_service_endpoint=$aquarius_service_endpoint"
CATALINA_OPTS="$CATALINA_OPTS -Dnwis_ra_home=$nwis_ra_home"
CATALINA_OPTS="$CATALINA_OPTS -Dnwis_ra_service_url=$nwis_service_endpoint"
CATALINA_OPTS="$CATALINA_OPTS -Dnwis_help_email=$nwis_help_email"